#!/usr/bin/env node
/**
 * Indify M0+ 工具:Dify 1.16.1 控制台 API 客户端(Node)。
 * 用法:
 *   node tools/dify-console.mjs login <email> <password>        # 登录并存 cookie 到 generated/m0/cookies.txt
 *   node tools/dify-console.mjs <VERB> <path> [bodyFile]        # GET/POST/PUT/DELETE /console/api/<path>
 *   node tools/dify-console.mjs <VERB> <path> --json '<json>'    # body 直接内联 JSON
 * 例:
 *   node tools/dify-console.mjs GET apps
 *   node tools/dify-console.mjs POST apps/imports --json '{"mode":"yaml-content","yaml_content":"..."}'
 *   node tools/dify-console.mjs GET apps/{id}/export --raw       # 打印原始响应体
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const BASE = process.env.DIFY_CONSOLE_URL ?? 'http://localhost/console/api';
const JAR = join(process.cwd(), 'generated', 'm0', 'cookies.txt');

function readJar() {
  if (!existsSync(JAR)) return { headers: {} };
  const cookies = {};
  for (const line of readFileSync(JAR, 'utf8').split(/\r?\n/)) {
    const l = line.replace(/^#HttpOnly_/, '').trim();
    if (!l || l.startsWith('#')) continue;
    const p = l.split('\t');
    if (p.length >= 7 && p[5]) cookies[p[5]] = p[6];
  }
  const cookieHeader = Object.entries(cookies).map(([k, v]) => `${k}=${v}`).join('; ');
  const headers = { cookie: cookieHeader };
  if (cookies.csrf_token) headers['x-csrf-token'] = cookies.csrf_token;
  return { headers, cookies };
}

async function rpc(verb, path, body, { raw = false, out } = {}) {
  const { headers } = readJar();
  const res = await fetch(`${BASE}/${path}`, {
    method: verb,
    headers: { ...headers, ...(body !== undefined ? { 'content-type': 'application/json' } : {}) },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (out) { writeFileSync(out, text, 'utf8'); console.log(JSON.stringify({ httpStatus: res.status, savedTo: out, bytes: text.length })); return res; }
  if (raw) { console.log(text); return res; }
  let json;
  try { json = JSON.parse(text); } catch { json = { raw: text.slice(0, 2000) }; }
  console.log(JSON.stringify({ httpStatus: res.status, body: json }, null, 2));
  return res;
}

async function login(email, password) {
  const b64 = Buffer.from(password, 'utf8').toString('base64');
  const res = await fetch(`${BASE}/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email, password: b64, language: 'zh-Hans', remember_me: true }),
  });
  const setCookies = res.headers.getSetCookie?.() ?? [];
  const jarLines = ['# Netscape HTTP Cookie File', '# generated by tools/dify-console.mjs'];
  const seen = new Set();
  for (const sc of setCookies) {
    const [pair, ...attrs] = sc.split(';').map((s) => s.trim());
    const eq = pair.indexOf('=');
    const name = pair.slice(0, eq);
    const value = pair.slice(eq + 1);
    const attrsMap = {};
    for (const a of attrs) {
      const i = a.indexOf('=');
      if (i > 0) attrsMap[a.slice(0, i).toLowerCase()] = a.slice(i + 1);
    }
    const httpOnly = attrsMap.httponly !== undefined;
    const secure = attrsMap.secure !== undefined;
    const domain = 'localhost';
    const path = attrsMap.path ?? '/';
    const expires = attrsMap.expires ? String(Math.floor(new Date(attrsMap.expires).getTime() / 1000)) : '0';
    const key = `${name}@${domain}${path}`;
    if (seen.has(key)) continue;
    seen.add(key);
    jarLines.push(`${httpOnly ? '#HttpOnly_' : ''}${domain}\tFALSE\t${path}\t${secure ? 'TRUE' : 'FALSE'}\t${expires}\t${name}\t${value}`);
  }
  writeFileSync(JAR, jarLines.join('\n') + '\n', 'utf8');
  console.log(JSON.stringify({ httpStatus: res.status, body: JSON.parse(await res.text()), cookiesSaved: setCookies.length }));
}

const [, , cmd, ...rest] = process.argv;
if (cmd === 'login') {
  await login(rest[0], rest[1]);
} else {
  let path = rest[0];
  let body;
  let raw = false;
  let out;
  const rawIdx = rest.indexOf('--raw');
  if (rawIdx >= 0) { raw = true; rest.splice(rawIdx, 1); }
  const outIdx = rest.indexOf('--out');
  if (outIdx >= 0) { out = rest[outIdx + 1]; rest.splice(outIdx, 2); }
  const yamlIdx = rest.indexOf('--yaml');
  if (yamlIdx >= 0) {
    const yaml = readFileSync(rest[yamlIdx + 1], 'utf8');
    body = { mode: 'yaml-content', yaml_content: yaml };
    rest.splice(yamlIdx, 2);
  }
  const jsonIdx = rest.indexOf('--json');
  if (jsonIdx >= 0) {
    body = JSON.parse(rest[jsonIdx + 1]);
  } else if (rest[1] && existsSync(rest[1])) {
    body = JSON.parse(readFileSync(rest[1], 'utf8'));
  } else if (rest[1]) {
    body = JSON.parse(rest[1]);
  }
  await rpc(cmd, path, body, { raw, out });
}
